### ISSUE TITLE
Questions regarding to choosing mergerfs over rclone union

### ISSUE THREAD

**Issue by theandychung** [blastbeng/MegaAccountGenerator#1]
I think this is the bash file I could reference or use for my pi, but I'm still not sure if I should use rclone union or mergerfs. Could you tell me why you chose mergerfs and not rclone union?

Thanks

**Comment by blastbeng** [comment]
This is an old project, when I wrote this code rclone union wasn't working that good if I remember correctly (es. Not working good with fstab or other problems) .
Anyways I guess rclone union is better than mergerfs now, you can try to adapt the code and open a pull request if you want.

**Comment by theandychung** [comment]
Got it, thanks. Do you know when you transfer data into or out of the mega pool created by your method (rclone + mergerfs), will it trigger all mega account to log in and out at the same time? I'm a bit worried that mega will not like the same IP log in and out massive accounts at the same time.

**Comment by blastbeng** [comment]
It will not like the same ip. That is why I kinda abandoned this project. You need something like Tor to anonimyze your ip on every mount. I tried that, one tor instance per mount but it was resource intensive process. Need a lot of ram and cpu.

**Comment by theandychung** [comment]
Sounds like rclone union would have the same issue.
Could you tell me what kind of behavior did mega do to user that log in with the same IP? Rejecting our log in or deleting our data completely?

**Comment by blastbeng** [comment]
They initially just bans the single account, but if you keep spamming creating new accounts, they will also ban your ip.

**Comment by theandychung** [comment]
Got it. Thanks!
